---
- hosts: localhost
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
  tasks:
    - name: test connection
      ping:
    - name: workstation packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - ansible
        - terminator
