---
# Tasks to be done as root
- hosts: localhost
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root
  tasks:
    - name: test connection
      ping:
    - name: apt repositories
      apt_repository:
        repo: "{{ item }}"
      with_items:
        - 'ppa:nextcloud-devs/client'
        - 'ppa:webupd8team/atom'
    - name: update apt cache
      apt:
        update_cache: true
      changed_when: false
    - name: workstation packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - ansible
        - terminator
        - atom
        - zsh
        - nextcloud-client
        - fonts-hack-web


# Tasks to be done as mike
- hosts: localhost
  vars:
    ansible_become: false
  tasks:
    - name: copy vimrc
      copy:
        src: files/vimrc
        dest: "{{ ansible_env.HOME }}/.vimrc"
    - name: copy terminator config
      copy:
        src: files/terminator
        dest: "{{ ansible_env.HOME }}/.config"
    - name: install oh-my-zsh
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
