---
# Tasks to be done as root
- hosts: localhost
  vars:
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_user: root

  handlers:
    - name: remove temp directory
      file:
        state: absent
        path: "{{ temp_directory.path }}"

  tasks:
    - package_facts:
        manager: apt
      tags: packages

    - name: allow nopasswd sudo
      lineinfile:
        dest: /etc/sudoers
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: apt keys
      tags: packages
      apt_key:
        url: "{{ item }}"
        state: present

      with_items:
        - https://packages.cloud.google.com/apt/doc/apt-key.gpg

    - name: update apt cache
      tags: packages
      apt:
        update_cache: true
      changed_when: false

    - name: workstation packages
      tags: packages
      apt:
        state: present
        name:
        - vim
        - terminator
        - zsh
        - fonts-hack-web
        - network-manager-openconnect
        - network-manager-openconnect-gnome
        - network-manager-l2tp
        - network-manager-l2tp-gnome
        - network-manager-openvpn
        - network-manager-openvpn-gnome
        - dkms
        - mesa-utils
        - whois
        - default-jre
        - gstreamer1.0-libav
        - qemu-kvm
        - libvirt-daemon
        - libvirt-clients
        - bridge-utils
        - virt-manager
        - gimp
        - ssh-askpass-fullscreen
        - awscli
        - nmap
        - jq
        - xournal
        - nfs-common
        - cowsay
        - apt-transport-https
        - pwgen
        - unzip
        - xclip
        - aptitude

    - name: Packages by URL
      tags: packages
      apt:
        deb: "{{ item.url }}"
      when: "item.name not in ansible_facts.packages"
      with_items:
        - url: https://downloads.slack-edge.com/releases/linux/4.34.120/prod/x64/slack-desktop-4.34.120-amd64.deb
          name: slack-desktop
        - url: https://zoom.us/client/latest/zoom_amd64.deb
          name: zoom
        - url: https://cdn.cloudflare.steamstatic.com/client/installer/steam.deb
          name: steam-launcher
        - url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
          name: code
        - url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
          name: 1password

    - name: local user shell
      user:
        name: "{{ ansible_env.SUDO_USER }}"
        shell: /usr/bin/zsh

    - name: Check installed 1Password version
      shell: /usr/local/bin/op --version
      register: op_install_check
      changed_when: no
      failed_when: no
      tags: opcli

    - name: Temp dir for download
      tempfile:
        state: directory
      register: temp_directory
      notify: remove temp directory
      when: op_install_check.stdout.find(opcli_version) == -1
      tags: opcli

    - name: Download OP zip
      get_url:
        url: "https://cache.agilebits.com/dist/1P/op/pkg/v{{ opcli_version }}/op_linux_amd64_v{{ opcli_version }}.zip"
        dest: "{{ temp_directory.path }}/op.zip"
        checksum: "sha256:{{ opcli_sha256 }}"
      when: op_install_check.stdout.find(opcli_version) == -1
      tags: opcli

    - name: Unzip OP
      unarchive:
        src: "{{ temp_directory.path }}/op.zip"
        dest: "{{ temp_directory.path }}"
        remote_src: yes
      when: op_install_check.stdout.find(opcli_version) == -1
      tags: opcli

    - name: Copy OP Binary
      copy:
        src: "{{ temp_directory.path }}/op"
        dest: /usr/local/bin/op
        remote_src: yes
        mode: 0755
        owner: root
        group: root
      when: op_install_check.stdout.find(opcli_version) == -1
      tags: opcli


# Tasks to be done as "{{ ansible_env.SUDO_USER }}"
- hosts: localhost
  tags: local_user
  vars:
    ansible_become: false
  tasks:
    - name: Home SSH directory
      file:
        dest: "{{ ansible_env.HOME}}/.ssh"
        state: directory
        mode: 0700

    - name: Copy SSH Config
      copy:
        src: ssh_config
        dest: "{{ ansible_env.HOME}}/.ssh/config"

    - name: home bin dir
      file:
        dest: "{{ ansible_env.HOME }}/.local/bin"
        state: directory

    - name: download aws zsh completion
      get_url:
        url: https://raw.githubusercontent.com/aws/aws-cli/develop/bin/aws_zsh_completer.sh
        dest: "{{ ansible_env.HOME }}/.local/bin/aws_zsh_completer.sh"
        mode: 0755

    - name: copy vimrc
      copy:
        src: files/vimrc
        dest: "{{ ansible_env.HOME }}/.vimrc"

    - name: copy terminator config
      copy:
        src: files/terminator
        dest: "{{ ansible_env.HOME }}/.config"

    - name: install oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"

    - name: .zsh directory
      file:
        dest: "{{ ansible_env.HOME }}/.zsh"
        state: directory

    - name: download docker tab completion
      get_url:
        url: https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker
        dest: "{{ ansible_env.HOME }}/.zsh"

    - name: copy zshrc
      template:
        src: files/zshrc.j2
        dest: "{{ ansible_env.HOME }}/.zshrc"

    - name: Download repo clone script
      get_url:
        url: https://gitlab.com/snippets/1943646/raw
        dest: "{{ ansible_env.HOME }}/.local/bin/clone_repo"
        mode: "0755"

    - name: Install tfenv
      git:
        repo: https://github.com/tfutils/tfenv.git
        dest: "{{ ansible_env.HOME }}/.tfenv"

    - name: Create symlinks for tfenv and terraform
      file:
        src: "{{ ansible_env.HOME }}/.tfenv/bin/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.local/bin/{{ item }}"
        state: link
      with_items:
      - tfenv
      - terraform

